# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c6f95434727dc4226ab3859ab9d9dfe08037eda175dc5fca1d526b8bc466f3ed27cb0d792e03d06e7e4396cfd98775c5fb88ead71354236ac8b5286920d5d31

test:
  secret_key_base: 2f0f1f6ee0c5b0973e087a1fa9232a13ba03310d29668f3fdb53e672a9928b08a43542b693817d270bf1d0baa8037e56504e393e4409b3f5786d685c0eab5e73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
