# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d714170a3403cc07290300a7f36b9f155f7364375d0a2b9bfebda9c457af59c116b93bee18ccbeb1aecec253c6aa1533a1f5ff2685020b984e58875bb5004597

test:
  secret_key_base: 65ece657ac3ba57eca8720a968711762835a086e6fb089c786ec14dc7d85dd92b74d977f68edba16e5e15ca169db58bb90e8a4693122ff32c8e90d68c189d7f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
